name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Notify Deployment
      run: |
        echo "Deployment successful! New changes have been deployed."
        # Aqui você pode adicionar um script para notificar ou realizar outras ações de deploy
