name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover

  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Microsoft Teams
        run: |
          curl -H 'Content-Type: application/json' -d '{"text": "Novo commit na branch main por '${{ github.actor }}'. Status: ${{ job.status }}"}' ${{ secrets.TEAMS_WEBHOOK_URL }}


